# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(height_field='height', upload_to='uploades/', width_field='width'),
        ),
    ]
