# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180924_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('thumb', models.ImageField(height_field='height', upload_to='thumbnails/', width_field='width')),
                ('img', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
            ],
        ),
    ]
