# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
