# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180924_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='img',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
