# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180930_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='thumbnails/'),
        ),
    ]
