# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20180930_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
    ]
