# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20181001_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
