# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20181015_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
